export const controls = [
  "                               ",
  "                               ",
  "       f                       ",
  "                               ",
  "       f                       ",
  "                               ",
  "       f                       ",
  "                               ",
  "       f                       ",
  "                               ",
  "       f                       ",
  "                               ",
  "       f                       ",
  "                               ",
  "       f                       ",
  "                               ",
  "       f                       ",
  "                               ",
  "                               ",
];
