export const menu = [
  "mppppppppppppppppppppppppppppppq",
  "n                              r",
  "n                              r",
  "n                              r",
  "n                              r",
  "n                              r",
  "n                         <===>r",
  "n                         [---]r",
  "n                         [---]r",
  "n                         [---]r",
  "n                       <=[---]r",
  "n<> @                   [-----]r",
  "n[]                     [-----]r",
  "n[]====>                [-----]r",
  "n[-----]                [-----]r",
  "n[-----]      <=====>   [-----]r",
  "n[-----]    <=[-----]   [-----]r",
  "n[-----]    [-------]   [-----]r",
  "n[-----]    (:::::::)   [-----]r",
  "osssssssssssssssssssssssssssssst",
];
